### ISSUE TITLE
Calendar.RecurrenceRule.recurrences(of:in) can find dates excluded by the range

### ISSUE THREAD

**Issue by Salynn** [swiftlang/swift-foundation#1040]
If a recurrence occurs on the upper bound of the limiting range, it is still included in the returned sequence. This violates the definition of Range<T> which states that the range does not include the upper bound. Either the type of the `of` parameter should be a ClosedRange for the current behavior, or the upper bound should be excluded from returned sequence.

```swift
let start = try Date.ISO8601FormatStyle().year().month().day().parse("2024-01-01")
let end = try Date.ISO8601FormatStyle().year().month().day().parse("2024-03-01")
let rule = Calendar.RecurrenceRule(calendar: .current, frequency: .monthly, matchingPolicy: .previousTimePreservingSmallerComponents)
for date in rule.recurrences(of: start, in: start..<end) {
    assert((start..<end).contains(date))
}
```

Expected behavior:
Code executes successfully

Actual behavior:
Code asserts on the last item in the sequence.

Also filed as [FB15728756](https://feedbackassistant.apple.com/feedback/15699570).

**Comment by Salynn** [comment]
Looks like the bug is on [Calendar_Recurrence.swift line 468](https://github.com/swiftlang/swift-foundation/blob/main/Sources/FoundationEssentials/Calendar/Calendar_Recurrence.swift#L468). The conditional check should be `>=` instead of `>`.
I'll see if I can get setup to test the fix and submit a PR.

**Comment by itingliu** [comment]
Fixed in https://github.com/swiftlang/swift-foundation/pull/1041
