### ISSUE TITLE
Windows file `URL` prepends "/" at beginning of `path` property, breaking compatibility

### ISSUE THREAD

**Issue by gregcotten** [swiftlang/swift-foundation#857]
For example, initialize a simple file URL and print its path:
```swift
let url = URL(fileURLWithPath: "C:/Test")
print(url.path)
```

In Swift 5.10.1, you get: `C:/Test`
In Swift 6.0 (August 7 snapshot) you get: `/C:/Test`

Maybe this is intended, but it definitely breaks my usage of passing file URL paths as arguments into a spawned `Process` for my build tools.

**Comment by jmschonfeld** [comment]
@jrflat I believe this is the new behavior of `URL`, so you might be able to look into this. @gregcotten I'd be interested hearing more about how this breaks your use of `Process` as I'd expect `Process` itself should still handle this (as `URL.withUnsafeFileSystemRepresentation` and `FileManager.fileSystemRepresentation` which are used to provide file system paths to C APIs should still handle this case and remove the leading slash) so at a minimum we should probably correct `Process` to account for this (I updated `Process` to correct the executable path with https://github.com/apple/swift-corelibs-foundation/pull/4999)

**Comment by gregcotten** [comment]
Interesting! I guess my issue with `path` being RFC8089 is that it's a rather large change, especially for me :) 

I often use `someURL.path` as a way of communicating a path to a non-Swift party, like calling out to an external process from Swift with a `someURL.path` as an argument, or in the case of our Electron app, communicating with their JS backend about presenting a save file dialog with a specified path, etc...

**Comment by jrflat** [comment]
@jmschonfeld Yeah I think we were just discussing there could be merit in moving Windows path logic (replacing `/` with `\`, removing leading slash if there's a drive letter) to `URL.fileSystemPath`, which is vended to `URL.path` for compatibility. I can look into that.

**Comment by dschaefer2** [comment]
Any update on this? @ahoppen mentioned it breaks sourcekit-lsp on Windows.

**Comment by jrflat** [comment]
Yes, apologies for the delay! Opened a PR to resolve the leading slash issue.

I think in the future it could also be a good idea for `URL.fileSystemPath` to convert all slashes to backslashes on Windows. Although, since `URL.fileSystemPath` and `URL.path` are synonymous, and this might further break `URL.path` compatibility, we'll hold off on that change for now.

**Comment by grynspan** [comment]
@jrflat Can we get this cherry-picked to release/6.0 for the next dot release?

**Comment by jrflat** [comment]
Yes for reference this is cherry-picked to `release/6.0` in #969 and `release/6.0.2` in #983

**Comment by ahoppen** [comment]
I’m still seeing this behavior in 6.0.2.

```
print(URL(string: "file:///C:/test.swift")!.path)
```
prints `/C:/test.swift`

Was this fix not cherry-picked to 6.0.2 after all

**Comment by jrflat** [comment]
This was cherry-picked to 6.0.2 in #983, I'll try to find a recent 6.0.2 Windows toolchain to confirm.

**Comment by jrflat** [comment]
@ahoppen works with this 6.0.2 toolchain https://ci-external.swift.org/job/swift-6.0.2-windows-toolchain-arm64/12/artifact/build/artifacts/

**Comment by gregcotten** [comment]
Works for me on the Windows 6.0.2 x86_64 release toolchain available on https://swift.org/download

**Comment by ahoppen** [comment]
Ah, I think I forgot that there was still https://github.com/swiftlang/swift-foundation/issues/977. Sorry for the confusion.
