### ISSUE TITLE
Getting path of Windows file URL adds a leading backslash before drive

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift-foundation#952]
```swift
import Foundation

let url = URL(string: "file:///c%3A/Users/alex")!
print(url.path)
```

Outputs `/c:/Users/alex`. As far as I can tell, the output should be `c:/Users/alex` (this is also what swift-corelibs-foundation produced).

**Comment by JacobHearst** [comment]
I believe this is the same issue that was reported in #857, can you confirm?

**Comment by ahoppen** [comment]
Yes, that appears to be the same issue. Closing as a duplicate.
