### ISSUE TITLE
[Windows] TimeZone.current returns GMT despite system settings

### ISSUE THREAD

**Issue by jmschonfeld** [swiftlang/swift-foundation#966]
Running `TimeZone.current` on Windows always returns GMT despite any present system settings.

This appears to be because on Windows we check `TZDEFAULT`: https://github.com/swiftlang/swift-foundation/blob/5141cf69577f26cdbabd65f6b12ff643b93f4685/Sources/FoundationEssentials/TimeZone/TimeZone_Cache.swift#L116-L131

However, `TZDEFAULT` does not appear to be set in the `WinSDK`/`ucrt` modules so we instead pickup the default value from our CShims: https://github.com/swiftlang/swift-foundation/blob/5141cf69577f26cdbabd65f6b12ff643b93f4685/Sources/_FoundationCShims/include/_CStdlib.h#L151-L157

These default paths seem unsuitable for Windows and result in us failing to detect the current timezone and falling back to GMT

**Comment by jmschonfeld** [comment]
@compnerd do you happen to know if we'd expect `TZDEFAULT` to be defined for Windows somewhere, or do we need to instead do something like what CoreFoundation has historically done: https://github.com/swiftlang/swift-corelibs-foundation/blob/e55e1d88001997be830fbc01086564431d405dad/Sources/CoreFoundation/CFTimeZone.c#L723-L734

**Comment by compnerd** [comment]
I don't expect `TZDEFAULT` to be set on Windows, we should be doing what CF did historically here.
