### ISSUE TITLE
`URL.path` includes leading Slash if the URL points to the root directory of a drive on Windows

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/swift-foundation#977]
```swift
print(URL(fileURLWithPath: #"C:\"#).path)
```

prints `/C:`. It should print `C:\`. 

Also see https://github.com/swiftlang/swift-foundation/issues/976, which is related.

**Comment by jmschonfeld** [comment]
I think this was likely resolved by https://github.com/swiftlang/swift-foundation/pull/964

**Comment by ahoppen** [comment]
It specific about `C:\`. I don't see the issue with non-root URLs
